export const UPDATE_EBOOK_TYPE = 'UPDATE_EBOOK_TYPE';
export const UPDATE_ORDER_BY = 'UPDATE_ORDER_BY';
export const UPDATE_PRINT_TYPE = 'UPDATE_PRINT_TYPE';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';