export const DELETE_BOOK_FROM_WANTED = 'DELETE_BOOK_FROM_WANTED';
export const ADD_BOOK_TO_WANTED_REQUEST = 'ADD_BOOK_TO_WANTED_REQUEST';
export const ADD_BOOK_TO_WANTED_SUCCESS = 'ADD_BOOK_TO_WANTED_SUCCESS';
export const UPDATE_SEARCH_WANTED_BOOKS_OPTIONS = 'UPDATE_SEARCH_WANTED_BOOKS_OPTIONS';
export const UPDATE_WANTED_SEARCH_FIELD = 'UPDATE_WANTED_SEARCH_FIELD';