export const DELETE_BOOK_FROM_WANTED = 'DELETE_BOOK_FROM_WANTED';
export const ADD_BOOK_TO_WANTED_REQUEST = 'ADD_BOOK_TO_WANTED_REQUEST';
export const ADD_BOOK_TO_WANTED_SUCCESS = 'ADD_BOOK_TO_WANTED_SUCCESS';