export const DELETE_BOOK_FROM_CART = 'DELETE_BOOK_FROM_CART';
export const CHANGE_BOOKS_AMOUNT = 'CHANGE_BOOKS_AMOUNT';
export const ADD_BOOK_TO_CART_REQUEST = 'ADD_BOOK_TO_CART_REQUEST';
export const ADD_BOOK_TO_CART_SUCCESS = 'ADD_BOOK_TO_CART_SUCCESS';