export const DELETE_BOOK_FROM_CART = 'DELETE_BOOK_FROM_CART';
export const CHANGE_BOOK_AMOUNT = 'CHANGE_BOOK_AMOUNT';
export const ADD_BOOK_TO_CART_REQUEST = 'ADD_BOOK_TO_CART_REQUEST';
export const ADD_BOOK_TO_CART_SUCCESS = 'ADD_BOOK_TO_CART_SUCCESS';
export const CALCULATE_FINAL_PRICE = 'CALCULATE_FINAL_PRICE';