export const GET_PRODUCTS_BY_CATEGORY_REQUEST = "GET_PRODUCTS_BY_CATEGORY_REQUEST";
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS = "GET_PRODUCTS_BY_CATEGORY_SUCCESS";
export const GET_PRODUCTS_BY_SEARCH_QUERY_REQUEST = "GET_PRODUCTS_BY_SEARCH_QUERY_REQUEST";
export const GET_PRODUCTS_BY_SEARCH_QUERY_SUCCESS = "GET_PRODUCTS_BY_SEARCH_QUERY_SUCCESS";

export const API_ERROR = "API_ERROR";