export const GET_PRODUCTS_BY_CATEGORY_REQUEST = "GET_PRODUCTS_BY_CATEGORY_REQUEST";
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS = "GET_PRODUCTS_BY_CATEGORY_SUCCESS";
export const API_ERROR = "API_ERROR";