export const GET_PRODUCTS_BY_OPTIONS_REQUEST = "GET_PRODUCTS_BY_OPTIONS_REQUEST";
export const GET_PRODUCTS_BY_OPTIONS_SUCCESS = "GET_PRODUCTS_BY_OPTIONS_SUCCESS";
export const SET_PROCESSING_FALSE = "SET_PROCESSING_FALSE";
export const SET_PROCESSING_TRUE = "SET_PROCESSING_TRUE";
export const CLEAR_BOOKS = "CLEAR_BOOKS ";
export const NON_BOOKS_FIND_ERROR = "NO_BOOKS_FIND_ERROR";
export const API_ERROR = "API_ERROR";