export const UPDATE_SEARCH_FIELD = "UPDATE_SEARCH_FIELD";
export const GET_PRODUCTS_BY_SEARCH_QUERY_REQUEST = "GET_PRODUCTS_BY_SEARCH_QUERY_REQUEST";
export const GET_PRODUCTS_BY_SEARCH_QUERY_SUCCESS = "GET_PRODUCTS_BY_SEARCH_QUERY_SUCCESS";